// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Exchange.Data.Models;

public partial class Net1810_212_1_ExchangeContext : DbContext
{
    public Net1810_212_1_ExchangeContext()
    {
    }

    public Net1810_212_1_ExchangeContext(DbContextOptions<Net1810_212_1_ExchangeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderType> OrderTypes { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<UserHave> UserHaves { get; set; }

    public virtual DbSet<UserWant> UserWants { get; set; }

  //  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
       // => optionsBuilder.UseSqlServer("Data Source=FAT-LAP\\PHAT_DB;Initial Catalog=Net1808_212_2_Exchange;User ID=sa;Password=12345");
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
             .AddJsonFile("appsettings.json")
           .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D8AF6B5150");

            entity.ToTable("Customer");

            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.District).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(50);
            entity.Property(e => e.Password)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(12)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Order__C3905BCF6F6339A6");

            entity.ToTable("Order");

            entity.Property(e => e.CompleDate).HasColumnType("date");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.OrderDate).HasColumnType("date");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.OrderType).WithMany(p => p.Orders)
                .HasForeignKey(d => d.OrderTypeId)
                .HasConstraintName("FK__Order__OrderType__4222D4EF");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D36CB99496A7");

            entity.ToTable("OrderDetail");

            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Message).HasMaxLength(50);
            entity.Property(e => e.Proposer)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderDeta__Order__4316F928");

            entity.HasOne(d => d.ProductUserHave).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductUserHaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__440B1D61");

            entity.HasOne(d => d.ProductUserWant).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductUserWantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__44FF419A");
        });

        modelBuilder.Entity<OrderType>(entity =>
        {
            entity.HasKey(e => e.OrderTypeId).HasName("PK__OrderTyp__23AC266C284D9E98");

            entity.ToTable("OrderType");

            entity.Property(e => e.OrderTypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Product__B40CC6CD78B90DEE");

            entity.ToTable("Product");

            entity.Property(e => e.Description).HasMaxLength(100);
            entity.Property(e => e.Img).HasColumnName("img");
            entity.Property(e => e.Origin).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Variation).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.Products)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Product__Custome__45F365D3");
        });

        modelBuilder.Entity<UserHave>(entity =>
        {
            entity.HasKey(e => e.ProductUserHaveId).HasName("PK__UserHave__631B3A5088B01CCF");

            entity.ToTable("UserHave");

            entity.Property(e => e.CreateDate).HasColumnType("date");
            entity.Property(e => e.Currency).HasMaxLength(10);
            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserHaves)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserHave__Produc__46E78A0C");
        });

        modelBuilder.Entity<UserWant>(entity =>
        {
            entity.HasKey(e => e.ProductUserWantId).HasName("PK__UserWant__24A6779F2A9D983C");

            entity.ToTable("UserWant");

            entity.Property(e => e.CreateDate).HasColumnType("date");
            entity.Property(e => e.Currency).HasMaxLength(10);
            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserWants)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__UserWant__Produc__47DBAE45");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}