// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Exchange.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateTime? CompleDate { get; set; }

    public int? TotalDiscount { get; set; }

    public int? TotalOrderQuantity { get; set; }

    public string Description { get; set; }

    public decimal TotalPrice { get; set; }

    public string Note { get; set; }

    public bool? UserHaveStatus { get; set; }

    public bool? UserWantStatus { get; set; }

    public int? OrderTypeId { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual OrderType OrderType { get; set; }
}