// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Exchange.Data.Models;

public partial class OrderType
{
    public int OrderTypeId { get; set; }

    public string OrderTypeName { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}