// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Exchange.Data.Models;

public partial class UserHave
{
    public int ProductUserHaveId { get; set; }

    public int ProductId { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public decimal GapPrice { get; set; }

    public int? Fax { get; set; }

    public string Note { get; set; }

    public DateTime? CreateDate { get; set; }

    public string Currency { get; set; }

    public int? Quantity { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }
}